AWSTemplateFormatVersion: "2010-09-09"
Description: Provision EC2
Parameters:
  UserName:
    Description: Enter user last name
    Type: String
  KeyName:
    Description: The EC2 Key pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"
  MyIP:
    Description: IP address allowed to access EC2
    Type: String
    Default: "0.0.0.0/0"
Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0218d08a1f9dac831
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue PublicSubnetA
          GroupSet:
            - !Ref EC2SG
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: 30
      UserData: 
        Fn::Base64: !Sub 
          - |
            #!/bin/bash
            localectl set-locale LAMG=en_US.UTF-8
            timedatectl set-timezone Asia/Tokyo
            sudo yum install -y yum-utils
            sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            sudo yum -y install terraform
            sudo yum -y install git
            export AWS_ACCESS_KEY_ID=AKIARXZXHXUXVYMYCD4R
            export AWS_SECRET_ACCESS_KEY=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
            export AWS_DEFAULT_REGION=ap-northeast-1
            export AWS_DEFAULT_OUTPUT=json
            aws s3 cp s3://iraha-cloudformation-backet/Secret/secret ~/.ssh/id_rsa
            aws s3 cp s3://iraha-cloudformation-backet/Secret/secret2 ~/.ssh/id_rsa.pub
            chmod 400 id_rsa
            aws s3 cp s3://iraha-cloudformation-backet/Secret/config ~/.ssh/config
            chmod 600 id_rsa
            git clone github:mototakairaha/TerraformAnsible.git
            git config --global user.email "mototaka.iraha@tafs.co.jp"
            git config --global user.name "mototaka.iraha"
            hostnamectl set-hostname ${UserName}-terraform
          - {
              UserName: !Ref UserName
            }

      Tags:
        - Key: Name
          Value: !Sub 'teraform-${UserName}'
        - Key: Owner
          Value: !Ref UserName
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${UserName}-ec2-sg'
      GroupDescription: Allow SSH
      VpcId: !ImportValue MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP

